name: Request hangs issue reproduction
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'

      - name: Run build
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'

      - name: Run build
        run: go build .

      - name: Run consumer test
        run:  go test -run ^TestConsumerV3$ .

      - name: Run provider test
        run:  go test -tags provider -run ^TestV3HTTPProvider$
