name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.6

    - name: Build
      run: go build -v ./...

    - name: Run consumer test
      run:  go test -run ^TestConsumerV3$ .

    - name: Run provider test
      run:  go test -tags provider -run ^TestV3HTTPProvider$
