name: Run tests

env:
  LD_LIBRARY_PATH: /tmp
  PACT_GO_LIB_DOWNLOAD_PATH: /tmp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.6

    - name: Install pact-go as a dev dependency
      run: GOBIN=$PWD/build go install github.com/pact-foundation/pact-go/v2@2.x.x

    - name: Download and install the required libraries
      run: $PWD/build/pact-go -l DEBUG install --libDir /tmp

    - name: Run consumer test
      run:  go test -run ^TestConsumerV3$ .

    - name: Run provider test
      run:  go test -tags provider -run ^TestV3HTTPProvider$
